basePath: /
definitions:
  request.CreateCursoRequest:
    properties:
      descripcion:
        type: string
      imagen_url:
        type: string
      nombre:
        type: string
    required:
    - nombre
    type: object
  request.CreateUnidadRequest:
    properties:
      nombre:
        type: string
    required:
    - nombre
    type: object
  request.UpdateValoracionRequest:
    properties:
      valoracion:
        type: number
    required:
    - valoracion
    type: object
  response.CrearCurso:
    properties:
      inserted_id:
        type: string
    type: object
  response.CrearUnidad:
    properties:
      inserted_id:
        type: string
    type: object
  response.CursoResponse:
    properties:
      cant_usuarios:
        type: integer
      comentarios:
        description: IDs de los comentarios
        items:
          type: string
        type: array
      descripcion:
        type: string
      id:
        type: string
      imagen_url:
        type: string
      nombre:
        type: string
      unidades:
        description: IDs de las unidades
        items:
          type: string
        type: array
      valoracion:
        type: number
    type: object
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  response.UnidadResponse:
    properties:
      clases:
        description: IDs de las clases en formato string
        items:
          type: string
        type: array
      id:
        type: string
      idcurso:
        type: string
      nombre:
        type: string
    type: object
  response.UpdateValoracionResponse:
    properties:
      message:
        type: string
      valoracion_actualizada:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta es una API para gestionar cursos y usuarios.
  title: API de Cursos y Usuarios
  version: "1.0"
paths:
  /api/cursos:
    get:
      consumes:
      - application/json
      description: Devuelve todos los cursos disponibles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CursoResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve todos los cursos
      tags:
      - Cursos
    post:
      consumes:
      - application/json
      description: Agrega un curso a la base de datos
      parameters:
      - description: Curso a crear
        in: body
        name: curso
        required: true
        schema:
          $ref: '#/definitions/request.CreateCursoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CrearCurso'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Crear un curso
      tags:
      - Cursos
  /api/cursos/{id}/unidades:
    get:
      consumes:
      - application/json
      description: Devuelve una unidades de un curso en específico dado su ID
      parameters:
      - description: ID del curso
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CursoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve unidades de un curso
      tags:
      - Unidades
    post:
      consumes:
      - application/json
      description: agregar una unidad a un curso
      parameters:
      - description: Unidad a crear
        in: body
        name: unidad
        required: true
        schema:
          $ref: '#/definitions/request.CreateUnidadRequest'
      - description: ID del curso
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.CrearUnidad'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Crear unidad
      tags:
      - Unidades
  /api/cursos/{id}/valoracion:
    patch:
      consumes:
      - application/json
      description: Actualiza la valoración de un curso según la nueva valoración proporcionada
      parameters:
      - description: ID del curso
        in: path
        name: id
        required: true
        type: string
      - description: Nueva valoración del curso
        in: body
        name: valoracion
        required: true
        schema:
          $ref: '#/definitions/request.UpdateValoracionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UpdateValoracionResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Actualiza la valoración de un curso
      tags:
      - Cursos
swagger: "2.0"
