basePath: /
definitions:
  response.CursoResponse:
    properties:
      cant_usuarios:
        type: integer
      comentarios:
        description: IDs de los comentarios
        items:
          type: string
        type: array
      descripcion:
        type: string
      id:
        type: string
      imagen_url:
        type: string
      nombre:
        type: string
      unidades:
        description: IDs de las unidades
        items:
          type: string
        type: array
      valoracion:
        type: number
    type: object
  response.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Esta es una API para gestionar cursos y usuarios.
  title: API de Cursos y Usuarios
  version: "1.0"
paths:
  /api/cursos:
    get:
      consumes:
      - application/json
      description: Devuelve todos los cursos disponibles
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.CursoResponse'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.ErrorResponse'
      summary: Devuelve todos los cursos
      tags:
      - Obtener cursos
swagger: "2.0"
